volumes:
  pgsqldata:
  pgsqlconf:
  pgsqllog:
  zabbixdata:
  grafanadata:

networks:
  network-zabbix:
    name: network-zabbix
    driver: bridge

services:
  zabbix-pgsql:
    container_name: zabbix-pgsql
    image: postgres:latest
    networks:
      - network-zabbix
    volumes:
      - pgsqldata:/var/lib/postgresql/data
      - pgsqlconf:/etc/postgresql
      - pgsqllog:/var/log/postgresql
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: zabbixdb
    ports:
      - '6543:5432'
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:latest
    networks:
      - network-zabbix
    links:
      - zabbix-pgsql
    volumes:
      - zabbixdata:/usr/lib/zabbix
    environment:
      DB_SERVER_HOST: zabbix-pgsql
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: zabbixdb
    depends_on:
      - zabbix-pgsql

  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-pgsql:latest
    networks:
      - network-zabbix
    links:
      - zabbix-pgsql
      - zabbix-server
    ports:
      - '3128:8080'
      - '443:8443'
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-pgsql
      POSTGRES_USER: zabbixcarese
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: zabbixdb
    depends_on:
      - zabbix-pgsql
      - zabbix-server
    
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - zabbix-pgsql
      - zabbix-server
    ports:
      - '3000:3000'
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - zabbix-pgsql
      - zabbix-server